### ISSUE TITLE
gobeansproxy build 出来之后 invalid memory address

### ISSUE THREAD

**Issue by yijia2413** [douban/gobeansproxy#4]
make 之后，运行 proxy，默认的配置文件,   ./proxy

```
[root@centos gobeansproxy]# ./proxy 
2018/12/09 22:56:48 gobeansproxy version 1.0.0.8
2018/12/09 22:56:48 server port: 7905, web port: 7908
2018/12/09 22:56:48 log to errorlog ./proxy-error.log
2018/12/09 22:56:48 open accesslog ./proxy-access.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x5e996f]

goroutine 1 [running]:
github.com/douban/gobeansproxy/dstore.NewManualScheduler(0x0, 0x3, 0x1)
        /home/golang/src/github.com/douban/gobeansproxy/dstore/scheduler.go:83 +0x5f
github.com/douban/gobeansproxy/dstore.InitGlobalManualScheduler(0x0, 0x3)
        /home/golang/src/github.com/douban/gobeansproxy/dstore/scheduler.go:77 +0x35
github.com/douban/gobeansproxy/gobeansproxy.Main()
        /home/golang/src/github.com/douban/gobeansproxy/gobeansproxy/gobeansproxy.go:57 +0x4d1
main.main()
        /home/golang/src/github.com/douban/gobeansproxy/main.go:8 +0x20

```

**Comment by ariesdevil** [comment]
@yijia2413 需要 `./proxy -confdir ./conf` 这样使用默认配置，我稍后更新一下 Readme

**Comment by yijia2413** [comment]
@ariesdevil   居然 Github 还有动静，给力……

我试试，自己用 Nginx 做 proxy 是不是也能达到同样的效果啊

**Comment by ariesdevil** [comment]
@yijia2413 这不是一个简单的转发 proxy，不能用 Nginx 替代，这个是走 Memcache 协议了，还做了 server 打分，路由等操作。
